[package]
name = "qobuz-player-tui"

version.workspace = true
edition.workspace = true
license-file.workspace = true
repository.workspace = true

[dependencies]
qobuz-player-controls= { version = "*", path = "../qobuz-player-controls" }

cursive = { workspace = true, features = ["crossterm-backend"] } 
futures = { workspace = true }
once_cell = { workspace = true }
tokio-stream = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }
gstreamer = { workspace = true, features = ["serde", "v1_16"] }
