[workspace]
members = [
  "qobuz-player-cli",
  "qobuz-player-controls",
  "qobuz-player-web",
  "qobuz-player-mpris",
  "qobuz-player-tui",
  "qobuz-player-client",
  "qobuz-player-gpio",
  "qobuz-player-rfid", "qobuz-player-database",
]
resolver = "2"

[workspace.package]
version = "0.2.9"
edition = "2024"
license-file = "LICENSE"
repository = "https://github.com/sofusa/qobuz-player"

[workspace.metadata.crane]
name = "qobuz-player"

[workspace.dependencies]
axum = "0.8"
axum-extra = { version = "0.10", features = ["cookie"] }
base64 = "0.22"
cached = "0.54"
chrono = "0.4"
clap = "4"
cursive =  "0.21"
dialoguer = "0.11"
dirs = "6"
futures = "0.3"
gstreamer = "0.23"
leptos = "0.8"
md5 = "0.7"
mime = "0.3"
mime_guess = "2"
rand = "0.9"
regex = "1"
reqwest = { version = "0.12", default-features = false }
serde = "1"
serde_json = "1"
snafu = "0.8"
sqlx = { version = "0.8", default-features = false }
tokio = "1"
tokio-stream = "0.1"
tracing = "0.1"
tracing-subscriber = "0.3"
url = "2"
