[workspace]
members = [
  "qobuz-player-cli",
  "qobuz-player-controls",
  "qobuz-player-tui",
  "qobuz-player-web",
  "qobuz-api",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
license-file = "LICENSE"
repository = "https://github.com/sofusa/qobuz-player"

[workspace.metadata.crane]
name = "qobuz-player"

[workspace.dependencies]
async-broadcast = "0.7"
async-trait = "0.1.73"
axum = "0.8"
base64 = "0.22"
cached = "0.50"
chrono = "0.4"
clap = "4"
ctrlc = "3.0"
cursive = { version = "0.20", default-features = false }
dialoguer = "0.11"
dirs = "5"
flume = "0.11"
futures = "0.3"
gstreamer = "0.23"
leptos = "0.7"
md5 = "0.7.0"
mime = "0.3"
mime_guess = "2.0"
once_cell = "1.18"
rand = "0.8"
regex = "1.5"
reqwest = { version = "0.12", default-features = false }
serde = "1.0"
serde_json = "1.0"
snafu = "0.8"
sqlx = { version = "0.7", default-features = false }
tokio = "1.35"
tokio-stream = "0.1"
tracing = "0.1"
tracing-subscriber = "0.3"
url = "2.4"
zbus = { version = "4", default-features = false }

[profile.release]
lto = true
strip = true
debug = false
opt-level = "z"
codegen-units = 1
