[package]
name = "qobuz-player-mpris"
version.workspace = true
edition.workspace = true
license-file.workspace = true
repository.workspace = true

[dependencies]
qobuz-player-controls = { version = "*", path = "../qobuz-player-controls" }

gstreamer = { workspace = true, features = ["serde", "v1_16"] }
tracing = { workspace = true }
chrono = { workspace = true }
zbus = { workspace = true, features = ["tokio"] }
