name: On Pull Request To Main (MacOS)
on:
  pull_request:
    paths:
      - "**.rs"
      - "**/Cargo.lock"
      - "**/Cargo.toml"
    branches:
      - main
jobs:
  pre-merge:
    name: Pre-merge checks
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: npm install
        working-directory: qobuz-player-web
        run: npm install

      - name: Build styles
        working-directory: qobuz-player-web
        run: npm run build

      - name: Build player ${{ matrix.arch }} 
        run: cargo build --release
