name: Create release, build and upload artifacts (Linux)

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.*
jobs:
  create-build-upload:
    name: Build, package and publish
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        arch: [x86_64, aarch64]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y librust-glib-dev librust-gstreamer-dev npm

      - name: npm install
        working-directory: qobuz-player-web
        run: npm install

      - name: Build styles
        working-directory: qobuz-player-web
        run: npm run build

      - name: Build player ${{ matrix.arch }} 
        run: cargo build --release

      - name: Tar qobuz-player-${{ matrix.arch }}-unknown-linux-gnu.tar.gz
        run: tar -cvf qobuz-player-${{ matrix.arch }}-unknown-linux-gnu.tar.gz -C ./target/${{ matrix.arch }}-unknown-linux-gnu/release/ qobuz-player

      - name: Release ${{ matrix.arch }}-unknown-linux-gnu
        uses: softprops/action-gh-release@v1
        with:
          files: qobuz-player-${{ matrix.arch }}-unknown-linux-gnu.tar.gz
